### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ghost** [NorfairKing/the-notes#2]
I'm very new to haskell, but I would like to see what's going on here `:P`. I could not build it. That's what I tried:

```
 $ git clone https://github.com/NorfairKing/the-notes
 $ cd the-notes
 $ stack --version
Version 1.6.3 x86_64 hpack-0.20.0
 $ make
stack install
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      wl-pprint-extras: needed (>=3.5), couldn't resolve its dependencies
    needed for package HaTeX-3.16.2.0

--  Failure when adding dependencies:    
      HaTeX: needed (>=3.16 && <3.17), couldn't resolve its dependencies
    needed for package lambdatex-0.1.0.4

--  Failure when adding dependencies:    
      tagged: needed (>=0.8.5 && <1), 0.8.2 found (latest applicable is 0.8.5)
    needed for package semigroupoids-5.0.0.4

--  Failure when adding dependencies:    
      HaTeX: needed (>=3.16.2 && <3.17), couldn't resolve its dependencies
      lambdatex: needed (>=0.1.0.4 && <0.2), couldn't resolve its dependencies
    needed for package the-notes-0.1.0.0

--  Failure when adding dependencies:    
      semigroupoids: needed (>=3 && <6), couldn't resolve its dependencies
    needed for package wl-pprint-extras-3.5.0.5
makefile:35: recipe for target 'install' failed
make: *** [install] Error 1
 $ stack upgrade
Current Stack version: 1.6.3, available download version: 1.6.3
Skipping binary upgrade, you are already running the most recent version
```

**Comment by NorfairKing** [comment]
I just merged development (which does work) into master. Try again now.

**Comment by ghost** [comment]
Complains about lots of linking stuff

tried:

``` sh

# following this suggestion https://github.com/commercialhaskell/stack/issues/497#issuecomment-264529689
rm -rf ~/.stack
stack setup
make


[1 of 1] Compiling Main             ( /tmp/stack31006/Setup.hs, /tmp/stack31006/Setup.o )
Linking /home/masked/.stack/setup-exe-cache/x86_64-linux/tmp-setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 ...
/usr/bin/ld: /tmp/stack31006/Setup.o: relocation R_X86_64_32S against symbol `stg_bh_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/masked/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Simple__87.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
(...)
[ lots of lines with: /usr/bin/ld: /home/masked/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/ ]
```

**Comment by NorfairKing** [comment]
This new problem _is_ a `stack` problem. 

https://github.com/commercialhaskell/stack/issues/3518#issuecomment-355748503

You can also send me an email and I'll send you the pdf.

**Comment by NorfairKing** [comment]
Closing due to inactivity.

**Comment by ghost** [comment]
the stack problem is still active, and this issue is dependent of that issue

I'm not only interested in the pdf, also in the generation of pdf with that haskell code. I can wait to get everything
